.TH "42SH" "1" "March 16, 2014" "42sh 1\&.0\&.0"
.SH "NAME"
42sh
.SH "OVERVIEW"
A ecrire
.PP
.PD 0
.TP
\fI42sh\fP			42sh overview(this section)
.PD
.SH "DESCRIPTION"
Le shel de l ecole 42.
.SH "AUTHOR"
Fait par amorfan, bbouabou, mmartin, pberne et ytailor.
.SH "AVAILABILITY"
.PP
.PD 0
.TP
.PD
Primary site
.nf
none
.fi
.PP
Up\-to\-date source code
.PP
.SH "MAILING LISTS"
none
.SH "THE 42SH FAQ"
none
.SH "THE 42SH WEB PAGE"
none
.SH "THE 42SH USERGUIDE"
none
.SH "THE 42SH WIKI"
none
.SH "INVOCATION"
The following flags are interpreted buy the shell when invoked to determine
where the shell will read commands form:
.PP
.PD 0
.TP
.PD
\fB\-t\fP
Dissable the termcap mode.
.PP
.SH "COMPATIBILITY"
none
.SH "RESTRICTED SHELL"
none
.SH "STARTUP/SHUTDOWN FILES"
none
.SH "FILES"
none
.SH "SEE ALSO"
none
